name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: تنظیم محیط پایتون
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: نصب وابستگی‌ها
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: اجرای ربات
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        python bot.py
